# Generated by Django 3.2.3 on 2021-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=60, verbose_name='Назва')),
                ('color', models.CharField(choices=[('ff0000', 'Червоний'), ('00ff00', 'Зелений'), ('0000ff', 'Синій')], max_length=6, verbose_name='Колір')),
                ('preview', models.ImageField(upload_to='category_images/')),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Зміст коментару')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Назва')),
                ('description', models.TextField(blank=True, max_length=2500, verbose_name='Опис')),
                ('site', models.URLField(blank=True, verbose_name='URL сайта')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Вміст')),
                ('likes', models.IntegerField(default=0, editable=False, verbose_name='Лайки')),
                ('dislikes', models.IntegerField(default=0, editable=False, verbose_name='Дизлайки')),
                ('preview', models.ImageField(upload_to='post_previews')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.Category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
                'default_permissions': (),
            },
        ),
    ]
