# Generated by Django 3.2.3 on 2021-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=60, verbose_name='Назва')),
                ('color', models.CharField(choices=[('ff0000', 'Червоний'), ('00ff00', 'Зелений'), ('0000ff', 'Синій')], max_length=6, verbose_name='Колір')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Зміст коментару')),
                ('Дата створення', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Назва')),
                ('description', models.TextField(blank=True, max_length=2500)),
                ('site', models.URLField(blank=True, verbose_name='URL сайта')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Вміст')),
                ('likes', models.IntegerField(verbose_name='Лайки')),
                ('dislikes', models.IntegerField(verbose_name='Дизлайки')),
                ('preview', models.ImageField(upload_to='post_previews')),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category', verbose_name='Категорії')),
            ],
        ),
    ]
