# Generated by Django 3.2.3 on 2021-05-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210516_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.ImageField(default='', upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
